# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fenestra_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(167, 128)
        self.centralwidget = QtWidgets.QWidget(LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_login = QtWidgets.QPushButton(self.centralwidget)
        self.btn_login.setGeometry(QtCore.QRect(30, 90, 101, 23))
        self.btn_login.setObjectName("btn_login")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(20, 10, 125, 69))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.ln_remote = QtWidgets.QLineEdit(self.splitter)
        self.ln_remote.setText("")
        self.ln_remote.setObjectName("ln_remote")
        self.ln_user = QtWidgets.QLineEdit(self.splitter)
        self.ln_user.setInputMask("")
        self.ln_user.setText("")
        self.ln_user.setObjectName("ln_user")
        self.ln_pass = QtWidgets.QLineEdit(self.splitter)
        self.ln_pass.setInputMask("")
        self.ln_pass.setText("")
        self.ln_pass.setObjectName("ln_pass")
        LoginWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "f.tea.p log.in"))
        self.btn_login.setText(_translate("LoginWindow", "Connect"))
        self.ln_remote.setPlaceholderText(_translate("LoginWindow", "remote host ip"))
        self.ln_user.setPlaceholderText(_translate("LoginWindow", "user name"))
        self.ln_pass.setPlaceholderText(_translate("LoginWindow", "password"))
